sonar.projectKey=transience_color-picker
sonar.organization=transience
sonar.source=./src
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.exclusions=**/stories/**/*.*,**/tests/**/*.*
sonar.coverage.exclusions=**/stories/**/*.*,**/tests/**/*.*,**/vitest.config.mts
